config/routes.rb
Credify::Application.routes.draw do

  resources :tasks
  resources :users
 resources :sessions, only: [:new, :create, :destroy]
    root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/task_done', to: 'tasks#assoc', via: 'get'
  match '/task_undone', to: 'tasks#disassoc', via: 'get'
  match '/redeem', to: 'static_pages#redeem', via: 'get'
  end

app/models/task.rb
class Task < ActiveRecord::Base
has_and_belongs_to_many :users
validates :name, presence: true
validates :value, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :tasks
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 },
                    uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
  end

  def create
      user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
       redirect_back_or user
      # Sign the user in and redirect to the user's show page.
    else
      flash.now[:error] = 'Invalid email/password combination'
    render 'new' 
  end
  end

  def destroy
  sign_out
  redirect_to root_url
  end
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
    
  end
  def contact
    
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
   before_action :admin_user,     only: [:destroy,:new]
  def new
    @task = Task.new
  end
  def create
    @task = Task.new(task_params)    # Not the final implementation!
    if @task.save
      redirect_to @task
    else
      render 'new'
    end
    end
    def show
    @task = Task.find(params[:id])
  end
def index
     @tasks = Task.paginate(page: params[:page])
  end
  def edit
     @task = Task.find(params[:id])
  end

  def delete
  end
  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Task updated"
      redirect_to @task
    else
      render 'edit'
    end
  end
def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Task deleted."
    redirect_to tasks_url
  end
  def assoc
     @user = current_user
      @task = Task.find(params[:id])
    @task.users << current_user
   redirect_to @user
  end
  def disassoc
      @user = current_user
      @task = Task.find(params[:id])
    @task.users.delete(current_user)
   redirect_to  @user
    
  end
  private
def task_params
      params.require(:task).permit(:name, :value)
    end
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

     def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
   before_action :admin_user,     only: :destroy
 def show
    @user = User.find(params[:id])
    @completetask = @user.tasks
    @incompletetask = Task.all
    @completed = @user.task_ids
    
      end
 def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Credify!"
      redirect_to @user
    else
      render 'new'
    end
    end
  
  def new
    @user = User.new
  end 
  def index
     @users = User.paginate(page: params[:page])
  end
  def edit
     @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  
     private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Credify"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
   def signed_in?
    !current_user.nil?
  end
   def current_user=(user)
    @current_user = user
  end
   def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def current_user?(user)
    user == current_user
  end
   def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
 
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <h2><%= link_to "Credify", root_path, id: "logo" %></h2>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Tasks", tasks_path%></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
                <li><%= link_to "Add task", new_task_path %></li>
                <li><%= link_to "Redeem", redeem_path %>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    	 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_completed.html.erb
<h1>Completed tasks</h1>


<ul class="tasks">
    <% @completetask.each do |task| %>
<li><h3><%= task.name%>
	<%= task.value%></h3><% @credit = @credit + task.value %>
<%= link_to "task incomplete", task_undone_path(id: task.id), class:"btn btn-danger"%>
</li>

<% end %>
</ul>

app/views/shared/_task_incomplete.html.erb
<h1>Incomplete tasks</h1>


<ul class="tasks">
    <% @incompletetask.each do |task| %>
    <% if task.id.in? @completed %>
    <% else %>
<li><h3>
	
	
	<%= task.name %>
	<%= task.value %></h3>
	<%= link_to "task completed", task_done_path(id: task.id), class:"btn btn-success"%>
</li>
<% end %>
<% end %>
</ul>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
      The core strategy of credify is to provide rewards to employees for accomplishing a specific task.
      the reward point may include achievement badges,points,levels or virtual currency.
      WORK MORE,SHOP MORE!!!
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
 Vishwesh S Shivapuja   <br>contact no:+91-9901777741
 </p>
 <p>
 	Karthik R Rao   <br>contact no:+91-9611965557
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
      Contact admin
    </p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <% if signed_in? %>
  
  <h1>Welcome <%= current_user.name %></h1>
  
  <%= link_to "Continue", user_path(current_user), class: "btn btn-large btn-primary" %>
  
  <% else %>
  <h1>Welcome to Credify</h1>

  <h2>
    WORK MORE,SHOP MORE!!
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>


<% end %>

app/views/static_pages/redeem.html.erb
<% provide(:title, 'Redeem') %>
<h1>Redeem</h1>
<p> You can redeem your credits at our <a href="http://www.flipkart.com/">partnerships</a>
<p>To avail cash benifit please send a request to the company manager</p>
  
</p>

app/views/tasks/_task.html.erb
<li>
	<%= link_to task.name, task %>
    <% if current_user.admin? %>
    | <%= link_to "delete", task, method: :delete,
                                  data: { confirm: "You sure?" } %>
  | <%= link_to "edit",  edit_task_path(task.id)%>
  <% end %>
</li>

app/views/tasks/edit.html.erb
<% provide(:title, "Edit task") %>
<h1>Update task</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@task) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>
  

      <%= f.label :task ,"task name"%>
      <%= f.text_field :name %>

      <%= f.label :value ,"credit value" %>
      <%= f.text_field :value %>

  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<% provide(:title, 'All tasks') %>
<h1>All task</h1>

<%= will_paginate %>

<ul class="tasks">
    <%= render @tasks %>
</ul>

<%= will_paginate %>

app/views/tasks/new.html.erb
<% provide(:title, 'Create task') %>
<h1>Create task</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@task) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :task ,"task name" %>
      <%= f.text_field :name %> 

      <%= f.label :value ,"credit value" %>
      <%= f.text_field :value %>
  <%= f.submit "Create new task", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, @task.name) %>
<div class="row">
  <aside class="span4">
    <section>
<h1>
	<%= @task.name %></h1>
<%= @task.name %>, <%= @task.value %>
 </section>
  </aside>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  
                            
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages',object: f.object %>
  

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %> 

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
<h1>
	 <%= gravatar_for @user %>
	<%= @user.name %></h1>
<h3> <%= @user.email %></h3>
<% @credit = 0 %>
 </section>
  </aside>
  </div>
  <div class="row">
  <div class="span6">
  	<%=render 'shared/task_completed' %>
  	</div>
  	<div class="span6">
  		<%=render 'shared/task_incomplete'%>
  	</div>
	
</div> <h2>Total Credits <%= @credit%></h2> 	
</div>